name: Build (Java 11)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "11"
          cache: maven

      - name: Build with Maven
        run: mvn -B -e -DskipTests package

      - name: Show built files
        run: ls -al target || true

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: WildRandom-jar
          path: |
            target/WildRandom-*.jar
          if-no-files-found: error
          retention-days: 14
